
# External gems
gems:
  # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Art_En
subtitle: "Tips and tricks on how i improved my art and running an instagram account."
email: art.en@yahoo.com
name: Emma Neill
description: > 
    Tips and tricks on how i improved my art and running an instagram account.
baseurl: "/centrarium/" # the subpath of your site, e.g. /blog/
url: "http://bencentra.github.io" # the base hostname & protocol for your site
cover: "assets/image (1).jpg"
logo: "assets/35102259.jpeg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives: 
#   enabled: 
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Disqus comments
disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: art
    desc: "Posts of my art"

  - cat: videos
    desc: "Videos of me creating my art"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Youtube
    icon: youtube
    username: art_en
    url:  https://www.youtube.com/channel/UCY0G1gL1nYKKNlOFHyf1N-w
    desc: Subscribe on Youtube
    share: true

  - name: Instagram
    icon: instagram
    username: art_en
    url: https://www.instagram.com/art_en 
    desc: Follow me on Instagram
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
